### ISSUE TITLE
Live currency formatting

### ISSUE THREAD

**Issue by lfarah** [nonameplum/CurrencyTextField#1]
I'd be better to format the currency string as the user is writing, just like [MoneyTextField](https://github.com/stripe/ios-dashboard-ui#moneytextfield) does

**Comment by nonameplum** [comment]
I think that this is different scenario that I wanted to accomplish. Probably picking another component for case that you described would be a better idea.

Thanks for the link to the great component!

**Comment by HardikDG** [comment]
I also like the idea of live formatting. PLCurrencyTextField looks good. It will be great if we have some feature like live formatting. 
Is there any update on this part?
