### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [nonameplum/CurrencyTextField#3]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by nonameplum** [comment]
Hey, It shouldn't be a problem. I will do this soon 😄

**Comment by nonameplum** [comment]
Migrated to Swift 3.0 https://github.com/nonameplum/PLCurrencyTextField/commit/483408b2134d3e3c92646ca66b81f48820645e63 . Swift 2.2 is now in the branch https://github.com/nonameplum/PLCurrencyTextField/tree/swift_2.2

**Comment by nonameplum** [comment]
@lfarah  Migrated to Swift 3.0 https://github.com/nonameplum/PLCurrencyTextField/commit/483408b2134d3e3c92646ca66b81f48820645e63 . Swift 2.2 is now in the branch https://github.com/nonameplum/PLCurrencyTextField/tree/swift_2.2
